// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slbvgfrhbiutcoiutapw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsYnZnZnJoYml1dGNvaXV0YXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMDU4NzAsImV4cCI6MjA3MTU4MTg3MH0.WFx7aFgiE6oZiUv04Y3NYESY9fM_F597Da31U06AqZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});